word_List = [
    "merhaba", "dünya", "python", "programlama", "veri", "bilimi", "yapay", "zeka", "makine", "öğrenimi",
    "doğal", "dil", "işleme", "analiz", "kodlama", "geliştirme", "kütüphane", "kurs", "ders", "ödev",
    "proje", "başarı", "başlangıç", "bitiş", "çalışma", "planlama", "hedef", "motivasyon", "başarı", "başarı",
    "başarı", "kitap", "yazar", "okuma", "kitaplık", "kütüphane", "kültür", "sanat", "müzik", "film", "oyun",
    "spor", "sağlık", "mutluluk", "huzur", "arkadaş", "aile", "topluluk", "hayat", "düşünce", "fikir", "özgürlük",
    "bilgi", "teknoloji", "internet", "web", "site", "uygulama", "mobil", "telefon", "bilgisayar", "donanım",
    "yazılım", "geliştirici", "mühendis", "programcı", "veritabanı", "network", "sunucu", "cloud", "bulut",
    "güvenlik", "siber", "siber güvenlik", "e-ticaret", "dijital", "pazarlama", "sosyal", "medya", "platform",
    "çevrimiçi", "online", "offline", "düşük kod", "veri tabanı", "veri bilimi", "makine öğrenmesi",
    "derin öğrenme", "görüntü işleme", "ses işleme", "doğal dil işleme", "yapay sinir ağları", "algoritma",
    "kodlama", "programlama dili", "derleme", "yorumlama", "hata ayıklama", "test", "hata", "çözüm", "sorun",
    "proje yönetimi", "liderlik", "ekip", "takım", "işbirliği", "toplantı", "strateji", "plan", "hedef",
    "başarı", "başarısızlık", "fırsat", "tehdit", "risk", "sürdürülebilirlik", "yaratıcılık", "yenilik", "girişimcilik",
    "kariyer", "iş", "mülakat", "CV", "özgeçmiş", "başvuru", "staj", "eğitim", "öğretim", "üniversite",
    "lisans", "lisansüstü", "yüksek lisans", "doktora", "ders", "ders notu", "sınav", "proje", "bitirme",
    "mezuniyet", "akademik", "araştırma", "bilimsel", "çalışma", "kaynak", "makale", "kitap", "dergi",
    "konferans", "sempozyum", "tez", "ödev", "sunum", "özgeçmiş", "iş deneyimi", "beceri", "yetenek",
    "özgeçmiş", "kariyer hedefi", "iş ilanı", "mülakat", "referans", "teşekkür mektubu", "motivasyon mektubu",
    "hobi", "gezi", "spor", "koşu", "yürüyüş", "bisiklet", "kamp", "doğa", "yüzme", "müzik",
    "sinema", "tiyatro", "resim", "heykel", "sergi", "konser", "festival", "parti", "yemek",
    "restoran", "kahve", "çay", "kahvaltı", "öğle yemeği", "akşam yemeği", "tatlı", "kek", "pastane",
    "şekerleme", "mevsim", "ilkbahar", "yaz", "sonbahar", "kış", "hava", "sıcak", "soğuk", "rüzgarlı",
    "yağmurlu", "karlı", "bulutlu", "güneşli", "doğa", "orman", "dağ", "göl", "deniz", "plaj",
    "kum", "kaya", "gökyüzü", "gökyüzü", "yıldız", "ay", "güneş", "gece", "gündüz", "vakit"
]
